### ISSUE TITLE
Error when running seed.exs

### ISSUE THREAD

**Issue by cdesch** [Cinderella-Man/toretto#53]
I ran into this error when getting setup with the readme process:
```
docker-compose up -d
mix deps.get
cd apps/ui/assets && npm install && cd ../../..
cd apps/hefty && mix ecto.reset && cd ../..
```

when running `cd apps/hefty && mix ecto.reset && cd ../..` i get the following error
```
20:06:53.661 application=ecto_sql module=Ecto.Migration.Runner [info] == Migrated 20190820071000 in 0.0s
20:06:53.677 application=ecto_sql module=Ecto.Migration.Runner [info] == Running 20190911200414 Hefty.Repo.Migrations.CreateSettingsTable.change/0 forward
20:06:53.677 application=ecto_sql module=Ecto.Migration.Runner [info] create table settings
20:06:53.680 application=ecto_sql module=Ecto.Migration.Runner [info] == Migrated 20190911200414 in 0.0s
20:06:59.217 [info] Fetching exchange info to retrieve assets and symbols
** (MatchError) no match of right hand side value: {:error, {:http_error, %HTTPoison.Error{id: nil, reason: {:option, :server_only, :honor_cipher_order}}}}
    priv/repo/seeds.exs:111: (file)
    (elixir) lib/code.ex:813: Code.require_file/2
    (mix) lib/mix/tasks/run.ex:145: Mix.Tasks.Run.run/5
    (mix) lib/mix/tasks/run.ex:85: Mix.Tasks.Run.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:365: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:292: Mix.Task.run/2
    (mix) lib/mix/task.ex:365: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:292: Mix.Task.run/2
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

I looks like the migrations run fine but there is an issue with the `seed.exs` 

is there some binance configuration that needs to be done?

**Comment by cdesch** [comment]
I did put the `api_key` and `secret` in `config.exs`.... still get the same error

**Comment by ghost** [comment]
https://github.com/benoitc/hackney/issues/591

**Comment by cdesch** [comment]
thanks. I made the [pull request on the binance.ex library to fix](https://github.com/dvcrn/binance.ex/pull/30)
